/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSpacePro: typeof import('./../src/components/ElSpacePro.vue')['default']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GlobalImagePreview: typeof import('./../src/components/GlobalImagePreview.vue')['default']
    GlobalModalRenderer: typeof import('./../src/components/GlobalModalRenderer.vue')['default']
    'ICustomBrand158_吃瓜': typeof import('~icons/custom-brand/158_吃瓜')['default']
    'ICustomBrand158_调皮': typeof import('~icons/custom-brand/158_调皮')['default']
    ICustomUiAly: typeof import('~icons/custom-ui/aly')['default']
    ICustomUiEle: typeof import('~icons/custom-ui/ele')['default']
    IframePageContent: typeof import('./../src/components/IframePageContent.vue')['default']
    IRiCloseLine: typeof import('~icons/ri/close-line')['default']
    IRiFullscreenExitLine: typeof import('~icons/ri/fullscreen-exit-line')['default']
    IRiFullscreenLine: typeof import('~icons/ri/fullscreen-line')['default']
    IRiLockFill: typeof import('~icons/ri/lock-fill')['default']
    IRiMenuFoldLine: typeof import('~icons/ri/menu-fold-line')['default']
    IRiMenuUnfoldLine: typeof import('~icons/ri/menu-unfold-line')['default']
    IRiMoreLine: typeof import('~icons/ri/more-line')['default']
    IRiRefreshLine: typeof import('~icons/ri/refresh-line')['default']
    IRiUserFill: typeof import('~icons/ri/user-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
