/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'NotFound404': RouteRecordInfo<
      'NotFound404',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Dashboard': RouteRecordInfo<
      'Dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'IframePage': RouteRecordInfo<
      'IframePage',
      '/iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | 'NotFound404'
      views:
        | never
    }
    'src/pages/auth/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | 'Dashboard'
      views:
        | never
    }
    'src/pages/iframe/index.vue': {
      routes:
        | 'IframePage'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
