name: 打包并输出到preview分支进行预览

# 检测只有主分支的push操作会触发该工作流
on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:
    name: 打包
    runs-on: ubuntu-latest

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有分支的信息和历史

      - name: 切换到main分支
        run: git checkout main

      - name: 指定Node.js版本
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装pnpm
        run: npm install pnpm -g

      - name: 安装依赖
        run: pnpm install

      - name: 打包
        run: pnpm build

      - name: 克隆整个仓库
        run: |
          git clone . ../repo-clone
          cd ../repo-clone
          git checkout -b preview origin/preview || git checkout -b preview

      - name: 清理preview分支
        run: |
          cd ../repo-clone
          git rm -rf .

      - name: 移动打包结果
        run: |
          cp -r dist/* ../repo-clone

      - name: 提交更改
        run: |
          cd ../repo-clone
          git add .
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "打包预览 -$current_time"

      - name: 推送到preview分支
        run: |
          cd ../repo-clone
          git push origin preview -f
